name: Publish to NuGet

on:
  push:
    branches:
        - main
    paths-ignore:
        - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download Release Assets
      run: |
        mkdir -p release-assets
        curl -L -o release-assets/voices.zip https://github.com/Lyrcaxis/KokoroSharp/releases/download/v0.1.0/voices.zip
        curl -L -o release-assets/espeak.zip https://github.com/Lyrcaxis/KokoroSharp/releases/download/v0.1.0/espeak.zip

    - name: Unzip Release Assets
      run: |
        unzip release-assets/voices.zip -d .
        unzip release-assets/espeak.zip -d .

    - run: dotnet build -c Release
    - run: dotnet pack -c Release
    - run: dotnet nuget push ./bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
