name: Publish to NuGet

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release-assets
          gh release download --repo $GITHUB_REPOSITORY --pattern 'voices.zip' --dir release-assets
          gh release download --repo $GITHUB_REPOSITORY --pattern 'espeak.zip' --dir release-assets

      - name: Unzip Release Assets
        run: |
          unzip release-assets/voices.zip -d voices
          unzip release-assets/espeak.zip -d espeak

      - run: dotnet build -c Release
      - run: dotnet pack -c Release
      - run: dotnet nuget push ./bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate